name: ebloffices
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dialogflow_grpc: ^0.2.9
  rxdart: 0.27.1
  sound_stream: 0.3.0
  kommunicate_flutter: ^1.2.0
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  google_sign_in: ^5.0.4
  sign_in_with_apple: ^3.0.0
  cloud_firestore: ^2.2.2
  photo_view: ^0.11.1
  flutter_rating_bar: ^4.0.0
  provider: ^5.0.0
  fluttertoast: ^8.0.7
  flutter_native_splash: ^1.2.0
  font_awesome_flutter: ^9.1.0
  url_launcher: ^6.0.7
  country_pickers: ^2.0.0
  maps_launcher: ^2.0.0
  shimmer: ^2.0.0
  getwidget: ^2.0.3
  flutter_staggered_grid_view: ^0.4.0

flutter_native_splash:
  background_image: assets/images/splashBack.png
  image: assets/images/ebloff.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/credentials.json
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
